#!/bin/bash
set -euo pipefail

go install -v ../../cmd/k6-to-honeycomb
go install 
(basic-example) &

k6 run -u 2 -d 20s --out json=./output.json --tag example_tag_1=foobar --tag=example_tag_2=banana basic-example.js

kill %1
wait
k6-to-honeycomb output.json
